window:
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10
font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic
  size: 13.0

# Colors (One Dark)
colors:
  primary:
    background: '#002b36'
    foreground: '#abb2bf'
  cursor:
    text:       CellBackground
    cursor:     '#528bff' # syntax-cursor-color
  selection:
    text:       CellForeground
    background: '#3e4451' # syntax-selection-color
  normal:
    black:      '#5c6370' # mono-3
    red:        '#e06c75' # red 1
    green:      '#98c379'
    yellow:     '#e5c07b' # orange 2
    blue:       '#61afef'
    magenta:    '#c678dd'
    cyan:       '#56b6c2'
    white:      '#828997' # mono-2
