vim.api.nvim_set_keymap('n', 'ms', ':Gvdiffsplit!<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'mo', '<C-W><C-O>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'gs', ':vert G<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'mh', ':diffget //2<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'ml', ':diffget //3<CR>', {noremap = true, silent = true})
