#!/bin/bash
echo "calling ssh_singularity with args $@"
ssh "$@"
# if [[ "${@: -1}" = *"no-singularity" ]]; then
#     # don't use singularity so we can use containers
#     echo "connecting without singularity"
#     ssh "$@"
# else
#     # use singularity
#     echo "connecting with singularity"
#     ssh -o RemoteCommand="/home/edwardr/git/aladdin/feature1/env/singularity.sh" -o RequestTTY=force "$@"
# fi
