#! /usr/bin/env zsh
SRC_DIR=$(realpath $(dirname $(realpath ${(%):-%x})))
DOT_DIR=$SRC_DIR/..

source $DOT_DIR/zsh/zprofile          # PATH setup (normally only loaded for login shells)
source $DOT_DIR/zsh/brew.zsh            # homebrew setup
source $DOT_DIR/zsh/base.zsh            # env + options + keybindings + vi mode + aliases
source $DOT_DIR/zsh/plugins/plugins.zsh # zsh plugins
source $DOT_DIR/zsh/fzf.zsh             # FZF integration
source $DOT_DIR/zsh/p10k.zsh            # theme

source $DOT_DIR/git/git.zsh             # git aliases, functions, and keybindings
source $DOT_DIR/tmux/tmux.zsh           # tmux shortcuts
source $DOT_DIR/node/node.zsh           # nvm setup
source $DOT_DIR/python/python.zsh       # python and pyenv setup
source $DOT_DIR/ocaml/ocaml.zsh         # opam configuration
source $DOT_DIR/ruby/rbenv.zsh          # rbenv setup

# Stash your environment variables in ~/.localrc or zshrc.secret. This means they'll stay out
# of your main dotfiles repository (which may be public, like this one), but
# you'll have access to them in your scripts.
if [[ -a ~/.localrc ]]; then
  . ~/.localrc
fi
if [[ -a $SRC_DIR/zshrc.secret ]]; then
    . $SRC_DIR/zshrc.secret
fi
